document.writeln("<!-- footer -->");
document.writeln("    <div class=\'footer\'>");
document.writeln("        <div class=\'f-cont\'>");
document.writeln("            <div class=\'f-info\'>");
document.writeln("                <div class=\'tel\'>");
document.writeln("                    <p class=\'num\' style=\'font-size: 18px;\'>010-56422901</p>");
document.writeln("                    <p class=\'time\'>9:00-18:00</p>");
document.writeln("                </div>");
document.writeln("                <p class=\'weibo\'>");
document.writeln("                    新浪官方微博<a href=\'javascript:;\'>");
document.writeln("                        <img src=\'http://photo.no5.com.cn/page_2014/images/guanzhu.jpg\' /></a></p>");
document.writeln("                <p class=\'ding\'><input type=\'text\' id=\'email\' value=\'请输入您的Email地址\' /><a href=\'javascript:;\'><img");
document.writeln("                            src=\'http://photo.no5.com.cn/page_2014/images/ding.jpg\' /></a>");
document.writeln("                </p>");
document.writeln("                <p class=\'ps\'>最新美容资讯，新品及促销信息</p>");
document.writeln("            </div>");
document.writeln("            <dl class=\'howto\'>");
document.writeln("                <dt><a href=\'javascript:;\'>如何订购</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>网上下单</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>电话订购</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>邮寄订购</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>传真订购</a></dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'howto\'>");
document.writeln("                <dt><a href=\'javascript:;\'>如何送货</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>送货上门</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>快递</a></dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'howto\'>");
document.writeln("                <dt><a href=\'javascript:;\'>如何付款</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>货到付款</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>在线支付</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>银行汇款</a></dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'howto\'>");
document.writeln("                <dt><a href=\'javascript:;\'>订单查询</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>订单状态</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>查询订单</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>无效订单</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>支付失败</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>缺货登记</a></dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'howto\'>");
document.writeln("                <dt><a href=\'javascript:;\'>会员服务</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>N°5购物保障</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>N°5贴心服务</a></dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'howto lastdl\'>");
document.writeln("                <dt><a href=\'javascript:;\'>联系我们</a></dt>");
document.writeln("                <dd><a href=\'javascript:;\'>关于N°5</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>加入N°5</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>团购加盟</a></dd>");
document.writeln("                <dd><a href=\'javascript:;\'>投诉</a><a href=\'javascript:;\'>建议</a></dd>");
document.writeln("            </dl>");
document.writeln("            <div class=\'wei\'><img src=\'http://photo.no5.com.cn/page_2014/images/2wm.jpg\' /></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'foot-bottom\'>");
document.writeln("        <dl class=\'fb\'>");
document.writeln("            <dt><img src=\'http://photo.no5.com.cn/page_2014/images/f_04.jpg\' /></dt>");
document.writeln("            <dd>足不出户 享受网购乐趣</dd>");
document.writeln("            <dd>北京城区次日送达</dd>");
document.writeln("        </dl>");
document.writeln("        <dl class=\'fb\'>");
document.writeln("            <dt><img src=\'http://photo.no5.com.cn/page_2014/images/f_05.jpg\' /></dt>");
document.writeln("            <dd>品质保证</dd>");
document.writeln("            <dd>15天不满意退换货</dd>");
document.writeln("        </dl>");
document.writeln("        <dl class=\'fb\'>");
document.writeln("            <dt><img src=\'http://photo.no5.com.cn/page_2014/images/f_06.jpg\' /></dt>");
document.writeln("            <dd>价格实惠 购物有积分</dd>");
document.writeln("            <dd>积分抵现金</dd>");
document.writeln("        </dl>");
document.writeln("        <dl class=\'fb\'>");
document.writeln("            <dt><img src=\'http://photo.no5.com.cn/page_2014/images/f_07.jpg\' /></dt>");
document.writeln("            <dd>1800多城市送货上门</dd>");
document.writeln("            <dd>货到付款</dd>");
document.writeln("        </dl>");
document.writeln("    </div>");
document.writeln("    <p class=\'beian\'>Copyright @ 2001-2020 N°5.com.cn All Rights Reserved 京ICP备11045170号&nbsp;|&nbsp;<a");
document.writeln("            href=\'http://photo.no5.com.cn/main/no5comcnyyzz.jpg\'>营业执照</a></p>");