document.writeln("    <!-- header -->");
document.writeln("    <div class=\'head-info\'>");
document.writeln("        <div class=\'infobox\'>");
document.writeln("            <div id=\'fs-toolbar1\' class=\'kfbox\'>");
document.writeln("                <dl class=\'top\'>");
document.writeln("                    <dt></dt>");
document.writeln("                    <dd>顶部</dd>");
document.writeln("                </dl>");
document.writeln("                <dl class=\'kf\'>");
document.writeln("                    <dt></dt>");
document.writeln("                    <dd>客服</dd>");
document.writeln("                </dl>");
document.writeln("            </div>");
document.writeln("            <ul class=\'head-welcome\'>");
document.writeln("                <li>您好，<b>欢迎光临No5时尚广场</b>。<span>[<a href=\'./login.html\'>登录</a>] [<a href=\'./register.html\'>免费注册</a>]</span></li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'user-control\'>");
document.writeln("                <li class=\'hide\'><a href=\'javascript:;\' class=\'\'>我的账户</a><b></b>");
document.writeln("                    <div class=\'myaccount\'>");
document.writeln("                        <p><a href=\'javascript:;\'>我的订单</a></p>");
document.writeln("                        <p><a href=\'javascript:;\'>我的积分</a></p>");
document.writeln("                        <p><a href=\'javascript:;\'>我的优惠券</a></p>");
document.writeln("                        <p><a href=\'javascript:;\'>我的收藏</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'line\'>|</li>");
document.writeln("                <li><a href=\'javascript:;\'>收藏本站</a></li>");
document.writeln("                <li class=\'line\'>|</li>");
document.writeln("                <li><a href=\'javascript:;\'>帮助中心</a></li>");
document.writeln("                <li class=\'tel\'><span></span>010-56422901</li>");
document.writeln("            </ul>");
document.writeln("            <div class=\'clear\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'headbox\'>");
document.writeln("        <div class=\'logo\'>");
document.writeln("            <a href=\'../index.html\'>");
document.writeln("                <img src=\'../images/common/logo.jpg\' />");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("        <div class=\'searchbox\'>");
document.writeln("            <div id=\'qrcode-box\'>");
document.writeln("                <ul id=\'mobile-menu\'>");
document.writeln("                    <li class=\'app\'><strong>app下载</strong>");
document.writeln("                        <p>");
document.writeln("                            <a href=\'javascript:;\' class=\'android\'></a>");
document.writeln("                            <a href=\'javascript:;\' class=\'ios\'></a>");
document.writeln("                        </p>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'gzh\'><strong>关注微信公众号</strong></li>");
document.writeln("                    <li></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'search\'>");
document.writeln("                <div id=\'search-helper\'></div>");
document.writeln("                <strong id=\'search-btn\'>搜索</strong>");
document.writeln("                <div class=\'del-keywords\'>×</div>");
document.writeln("                <input type=\'text\' id=\'search\' name=\'search\' value=\'护手霜\' old-data=\'护手霜\' accesskey=\'s\'");
document.writeln("                    autocomplete=\'off\' />");
document.writeln("            </div>");
document.writeln("            <div class=\'hot-key\'>热门搜索：");
document.writeln("                <a href=\'javascript:;\' class=\'\'>保湿</a>");
document.writeln("                <a href=\'javascript:;\' class=\'LETTER-RED\'>防敏感专用</a>");
document.writeln("                <a href=\'javascript:;\' class=\'\'>雅诗兰黛</a>");
document.writeln("                <a href=\'javascript:;\' class=\'\'>气垫bb</a>");
document.writeln("                <a href=\'javascript:;\' class=\'LETTER-RED\'>护手霜</a>");
document.writeln("                <a href=\'javascript:;\' class=\'\'>专柜小样</a>");
document.writeln("                <a href=\'javascript:;\' class=\'\'>口红</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <a href=\'../html/goodsShopcar.html\' id=\'page-cartbar\' class=\'shoppingcart\'>");
document.writeln("            <div class=\'trigger\' style=\'cursor: pointer;\'>购物车<strong>0</strong>件</div>");
document.writeln("            <div class=\'shoplist\'>");
document.writeln("                &nbsp;&nbsp;&nbsp;&nbsp;购物车中还没有商品，赶紧选购吧！");
document.writeln("            </div>");
document.writeln("        </a>");
document.writeln("    </div>");
document.writeln("    <div id=\'main-nav-repl\' style=\'height: 40px; display: none;\'></div>");
document.writeln("    <div id=\'main-nav\' class=\'mainnav\'>");
document.writeln("        <div class=\'navbox\'>");
document.writeln("            <div class=\'subnav\'>");
document.writeln("                <ul>");
document.writeln("                    <li style=\'background:none;\'><a href=\'../index.html\'>首页</a></li>");
document.writeln("                    <li><a href=\'javascript:;\'>超值小样</a></li>");
document.writeln("                    <li><a href=\'javascript:;\'>明星推荐</a></li>");
document.writeln("                    <li><a href=\'javascript:;\'>最新活动</a></li>");
document.writeln("                    <li><a href=\'javascript:;\'>新品上架</a></li>");
document.writeln("                    <li><a href=\'javascript:;\' class=\'LETTER-RED\'>本周特价</a></li>");
document.writeln("                    <li><a href=\'javascript:;\' class=\'LETTER-RED\'>清仓</a></li>");
document.writeln("                    <li><a href=\'javascript:;\'>品牌库</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <!--category nav begin-->");
document.writeln("            <div class=\'float-list shaixuan\' id=\'float-list\'>");
document.writeln("                <span class=\'float-list-btn\'>全部商品分类</span>");
document.writeln("            </div>");
document.writeln("            <!--category nav end-->");
document.writeln("        </div>");
document.writeln("    </div>");